name: Alittle
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: stephenwzl <stephenwzlwork@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  uuid: "^1.0.0"

dev_dependencies:
  test: ^0.12.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter